{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "marchproxy-egress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-egress.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "marchproxy-egress.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
