{{- if .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-ingress.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- if .Values.tls.clientCa }}
  ca.crt: {{ .Values.tls.clientCa | b64enc }}
  {{- end }}
{{- end }}
