apiVersion: v1
kind: Service
metadata:
  name: proxy-rtmp
  namespace: marchproxy
  labels:
    app.kubernetes.io/name: marchproxy
    app.kubernetes.io/component: proxy-rtmp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: marchproxy
    app.kubernetes.io/component: proxy-rtmp
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
  - name: hls-http
    port: 8081
    targetPort: 8081
  - name: admin
    port: 7005
    targetPort: 7005
  - name: grpc
    port: 50054
    targetPort: 50054
