apiVersion: v1
kind: Service
metadata:
  name: {{ include "marchproxy-egress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-egress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: tcp-proxy
      port: {{ .Values.service.tcpProxyPort }}
      targetPort: tcp-proxy
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
    - name: envoy-admin
      port: {{ .Values.service.envoyAdminPort }}
      targetPort: envoy-admin
      protocol: TCP
    - name: ext-auth
      port: {{ .Values.service.extAuthPort }}
      targetPort: ext-auth
      protocol: TCP
  selector:
    {{- include "marchproxy-egress.selectorLabels" . | nindent 4 }}
