apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marchproxy-beta

bases:
  - ../../base

nameSuffix: -beta
namePrefix: ""

replicas:
  - name: manager-deployment
    count: 2
  - name: proxy-deployment
    count: 2

commonLabels:
  environment: beta
  tier: staging

commonAnnotations:
  environment: "beta"
  deployment-version: "stable"

images:
  - name: marchproxy-manager
    newName: registry-dal2.penguintech.io/marchproxy-manager
    newTag: v1.0.4
  - name: marchproxy-webui
    newName: registry-dal2.penguintech.io/marchproxy-webui
    newTag: v1.0.0
  - name: marchproxy-proxy
    newName: registry-dal2.penguintech.io/marchproxy-proxy
    newTag: v1.0.0

patches:
  - target:
      kind: Namespace
      name: marchproxy
    patch: |-
      - op: replace
        path: /metadata/name
        value: marchproxy-beta

  - target:
      kind: Deployment
      name: manager-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: LOG_LEVEL
            value: "INFO"
          - name: ENVIRONMENT
            value: "beta"

  - target:
      kind: Deployment
      name: proxy-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: LOG_LEVEL
            value: "INFO"
          - name: ENVIRONMENT
            value: "beta"

  - target:
      kind: Ingress
      name: marchproxy-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: marchproxy.penguintech.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: marchproxy.penguintech.cloud

configMapGenerator:
  - name: marchproxy-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=beta

secretGenerator:
  - name: marchproxy-secrets
    behavior: merge
    literals:
      - CLUSTER_API_KEY=beta-api-key
