# Beta environment overrides (dal2 cluster)
namespace: marchproxy-beta
replicaCount: 2
image:
  registry: registry-dal2.penguintech.io
  pullPolicy: Always
env:
  LOG_LEVEL: INFO
  RELEASE_MODE: "false"
ingress:
  hosts:
    - host: marchproxy.penguintech.cloud
  tls:
    - secretName: penguintech-wildcard-tls
      hosts:
        - marchproxy.penguintech.cloud
