{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "marchproxy-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "marchproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-ingress.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "marchproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-ingress.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "marchproxy-ingress.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "marchproxy-ingress.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
