apiVersion: v1
kind: Service
metadata:
  name: {{ include "marchproxy-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marchproxy-ingress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if eq .Values.service.externalTrafficPolicy "Local" }}
  externalTrafficPolicy: Local
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.httpsNodePort }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "marchproxy-ingress.selectorLabels" . | nindent 4 }}
